name: Test deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      image:
        type: string
        description: Image URI
        required: true
      SLACK_WEBHOOK:
        type: string
        description: Slack webhook
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Intentional fail
        run: exit 1
      - name: Successful deploy notification
        uses: ./.github/workflows/actions/notify
        if: always()
        with:
          SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
