name: Test deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      image:
        type: string
        description: Image URI
        required: true
      SLACK_WEBHOOK:
        type: string
        description: Slack webhook
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Intentional fail
        run: exit 1
      - name: Successful deploy notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
          SLACK_USERNAME: AWS Deployment Bot
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Panacea deployment run
          SLACK_MESSAGE: Revision ${{ inputs.image-uri }} deployed to ${{ inputs.environment }}.
