name: Test deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      DEV_SLACK_WEBHOOK:
        type: string
        description: dev Slack webhook
        required: true
      STAGING_SLACK_WEBHOOK:
        type: string
        description: stag Slack webhook
        required: true
      PROD_SLACK_WEBHOOK:
        type: string
        description: prod Slack webhook
        required: true
jobs:
  determine-webhook:
    name: Determine which slack webhook to use
    runs-on: ubuntu-latest
    steps:
      - name: Use dev webhook
        if: contains(inputs.environment, 'dev')
        run: |
          echo "SLACK_WEBHOOK=${{inputs.DEV_SLACK_WEBHOOK}}" >> $GITHUB_ENV
      - name: Use staging webhook
        if: contains(inputs.environment, 'staging')
        run: |
          echo "SLACK_WEBHOOK=${{inputs.STAGING_SLACK_WEBHOOK}}" >> $GITHUB_ENV
      - name: Use prod webhook
        if: contains(inputs.environment, 'prod')
        run: |
          echo "SLACK_WEBHOOK=${{inputs.PROD_SLACK_WEBHOOK}}" >> $GITHUB_ENV
  deploy:
    name: Deploy
    needs: determine-webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo ${{ env.SLACK_WEBHOOK }}
      - name: Intentional fail
        run: exit 1
      - name: Successful deploy notification
        uses: ./.github/workflows/actions/deploy-notification
        if: always()
        with:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          environment: ${{ inputs.environment }}
